name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Check formatting
        run: cargo fmt -- --check
  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: [stable, beta, nightly]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{matrix.rust_version}}
            override: true
      - uses: Swatinem/rust-cache@v1
      - name: Test
        run: cargo test
